### Create AnswerReports
POST localhost:8080/api/reports/answers
Authorization: Basic asdf@gmail.com qweqwe123
content-type: application/json

{
  "reportReasonId": 1,
  "answerId": 1
}

### GET AnswerReports
GET localhost:8080/api/reports/answers
Authorization: Basic qwer@gmail.com qweqwe123

### handle AnswerReports
POST localhost:8080/api/reports/answers/1
Authorization: Basic qwer@gmail.com qweqwe123

### delete AnswerReports
DELETE localhost:8080/api/reports/answers/1
Authorization: Basic qwer@gmail.com qweqwe123