### 회원가입 API
POST localhost:8080/api/users/join
content-type: application/json

{
  "email": "gusckd57@naver.com",
  "password": "as661899",
  "nickname": "스윈"
}

### get me
GET localhost:8080/api/users/me
Authorization: Basic gusckd57@naver.com as661899

### delete me
DELETE localhost:8080/api/users/me
Authorization: Basic gusckd57@naver.com as661899